FROM maven:latest

# Set working directory
WORKDIR /app

# Copy everything into container
COPY . .

# Build the application
RUN mvn clean package

# Expose app port
EXPOSE 8786

# Run the JAR
CMD ["java", "-jar", "target/HelloApp-0.0.1-SNAPSHOT.jar"]


# if you copied the JAR to /app
# CMD ["java", "-jar", "app.jar"]

# older file config
# CMD ["java", "-jar", "target/*.jar"]
