apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-1
spec:
  selector:
    matchLabels:
      app: project-1
  template:
    metadata:
      labels:
        app: project-1
    spec:
      containers:
      - name: myapp
        image: jayeshdockerhub/project-1:version1
